-- CALENDAR_GOOGLE_AUTH
CREATE TABLE CALENDAR_GOOGLE_AUTH (
    DISCORD_USER_ID VARCHAR2(32) NOT NULL PRIMARY KEY,
    GOOGLE_USER_ID VARCHAR2(255),
    ACCESS_TOKEN VARCHAR2(4000),
    REFRESH_TOKEN VARCHAR2(4000),
    EXPIRY_DATE TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CALENDAR_USER_CALENDARS
CREATE TABLE CALENDAR_USER_CALENDARS (
    DISCORD_USER_ID VARCHAR2(32) NOT NULL,
    CALENDAR_ID VARCHAR2(255) NOT NULL,
    CALENDAR_NAME VARCHAR2(255),
    CONSTRAINT PK_CAL_USER_CAL PRIMARY KEY (DISCORD_USER_ID, CALENDAR_ID),
    CONSTRAINT FK_CAL_USER_CAL_USER FOREIGN KEY (DISCORD_USER_ID) REFERENCES CALENDAR_GOOGLE_AUTH(DISCORD_USER_ID) ON DELETE CASCADE
);

-- CALENDAR_SYNC_STATE
CREATE TABLE CALENDAR_SYNC_STATE (
    CALENDAR_ID VARCHAR2(255) NOT NULL PRIMARY KEY,
    SYNC_TOKEN VARCHAR2(255),
    LAST_SYNCED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CALENDAR_WATCH_CHANNELS
CREATE TABLE CALENDAR_WATCH_CHANNELS (
    CHANNEL_ID VARCHAR2(255) NOT NULL PRIMARY KEY, -- Google UUID
    CALENDAR_ID VARCHAR2(255) NOT NULL,
    RESOURCE_ID VARCHAR2(255),
    EXPIRATION TIMESTAMP
);
