CREATE TABLE CALENDAR_EVENTS (
    CALENDAR_ID VARCHAR2(255) NOT NULL,
    EVENT_ID VARCHAR2(255) NOT NULL,
    SUMMARY VARCHAR2(1000),
    DESCRIPTION VARCHAR2(4000),
    START_TIME TIMESTAMP WITH TIME ZONE,
    END_TIME TIMESTAMP WITH TIME ZONE,
    IS_ALL_DAY NUMBER(1) DEFAULT 0,
    LOCATION VARCHAR2(1000),
    STATUS VARCHAR2(50),
    HTML_LINK VARCHAR2(500),
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CALENDAR_EVENTS PRIMARY KEY (CALENDAR_ID, EVENT_ID)
);

CREATE INDEX IDX_CAL_EVENTS_TIME ON CALENDAR_EVENTS (START_TIME);
