CREATE TABLE CALENDAR_TodoCreateSessions (
  SESSION_ID NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(32) NOT NULL,
  PAYLOAD_TOKEN VARCHAR2(200) NOT NULL,
  PAGE_NUMBER NUMBER NOT NULL,
  CHANNEL_ID VARCHAR2(32) NOT NULL,
  MESSAGE_ID VARCHAR2(32) NOT NULL,
  TITLE VARCHAR2(256) NOT NULL,
  BODY CLOB,
  LABELS VARCHAR2(1000),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE SEQUENCE CALENDAR_TODO_CREATE_SESSIONS_SEQ
  START WITH 1
  INCREMENT BY 1;
