CREATE TABLE CALENDAR_GuildChannelConfig (
  GUILD_ID VARCHAR2(32) NOT NULL,
  CHANNEL_KEY VARCHAR2(64) NOT NULL,
  CHANNEL_ID VARCHAR2(32) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_CAL_GUILD_CHANNEL_CFG PRIMARY KEY (GUILD_ID, CHANNEL_KEY)
);

CREATE INDEX IDX_CAL_GUILD_CHANNEL_CFG_CHAN
ON CALENDAR_GuildChannelConfig (CHANNEL_ID);

